import { ArrowLeft, CheckCircle2, Eye, EyeOff, LoaderCircle, Mail } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import AuthLayout from '../layouts/AuthLayout';
import Button from '../components/Button';
import { useAuth } from '../context/AuthContext';

const fieldClass = 'mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-teal-100';
function ErrorText({ message }) { return message ? <p className="mt-1 text-xs font-medium text-red-600">{message}</p> : null; }
function PasswordField({ register, error, name = 'password', label = 'Password' }) { const [show, setShow] = useState(false); return <div><label className="text-sm font-medium text-slate-700">{label}<div className="relative"><input type={show ? 'text' : 'password'} className={`${fieldClass} pr-11`} {...register(name)} /><button type="button" aria-label={show ? 'Hide password' : 'Show password'} onClick={() => setShow(!show)} className="absolute right-3 top-3 text-slate-400">{show ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></label><ErrorText message={error?.message} /></div>; }
function makeToken(role) { return `header.${btoa(JSON.stringify({ role }))}.signature`; }
const loginSchema = z.object({ email: z.string().email('Enter a valid email address'), password: z.string().min(8, 'Password must be at least 8 characters') });
export function Login() { const navigate = useNavigate(); const { dispatch } = useAuth(); const [loading, setLoading] = useState(false); const { register, handleSubmit, formState: { errors } } = useForm({ resolver: zodResolver(loginSchema) }); const submit = (values) => { setLoading(true); window.setTimeout(() => { const role = values.email.includes('admin') ? 'ADMIN' : values.email.includes('ngo') ? 'NGO_STAFF' : values.email.includes('officer') ? 'OFFICER' : 'CITIZEN'; const token = makeToken(role); localStorage.setItem('clrms_token', token); dispatch({ type: 'LOGIN', payload: { token, role, user: { name: values.email.split('@')[0], role: role.replace('_', ' '), initials: values.email.slice(0, 2).toUpperCase() } } }); navigate({ CITIZEN: '/citizen/dashboard', OFFICER: '/staff/dashboard', NGO_STAFF: '/staff/dashboard', ADMIN: '/admin/dashboard' }[role]); }, 550); }; return <AuthLayout eyebrow="Welcome back" title="Sign in to CLRMS" subtitle="Your work helps children move toward safety and opportunity."><form onSubmit={handleSubmit(submit)} noValidate><label className="text-sm font-medium text-slate-700">Email address<div className="relative"><Mail className="absolute left-3 top-3 text-slate-400" size={18} /><input type="email" placeholder="you@example.org" className={`${fieldClass} pl-10`} {...register('email')} /></div></label><ErrorText message={errors.email?.message} /><div className="mt-5"><PasswordField register={register} error={errors.password} /></div><div className="mt-3 flex justify-end"><Link to="/forgot-password" className="text-sm font-semibold text-primary hover:underline">Forgot password?</Link></div><Button type="submit" disabled={loading} className="mt-7 flex w-full items-center justify-center">{loading ? <><LoaderCircle className="mr-2 animate-spin" size={18} />Signing in...</> : 'Sign in securely'}</Button><p className="mt-6 text-center text-sm text-slate-500">New to CLRMS? <Link to="/register" className="font-semibold text-primary">Create an account</Link></p></form></AuthLayout>; }
const citizenSchema = z.object({ name: z.string().min(2, 'Please enter your full name'), email: z.string().email('Enter a valid email address'), password: z.string().min(8, 'Password must be at least 8 characters') });
const officerSchema = citizenSchema.extend({ organization: z.string().min(2, 'Organization name is required'), designation: z.string().min(2, 'Designation is required'), jurisdiction: z.string().min(2, 'Jurisdiction is required') });
export function Register() { const [type, setType] = useState('citizen'); const [submitted, setSubmitted] = useState(false); const schema = type === 'citizen' ? citizenSchema : officerSchema; const { register, handleSubmit, formState: { errors } } = useForm({ resolver: zodResolver(schema) }); return <AuthLayout eyebrow="Join the network" title="Create your account" subtitle="Choose the account that best describes how you support children."><div className="grid grid-cols-2 rounded-xl bg-slate-100 p-1 text-sm font-semibold"><button type="button" onClick={() => { setType('citizen'); setSubmitted(false); }} className={`rounded-lg px-3 py-2.5 ${type === 'citizen' ? 'bg-white text-primary shadow-sm' : 'text-slate-500'}`}>Report as Citizen</button><button type="button" onClick={() => { setType('officer'); setSubmitted(false); }} className={`rounded-lg px-3 py-2.5 ${type === 'officer' ? 'bg-white text-primary shadow-sm' : 'text-slate-500'}`}>Officer / NGO</button></div>{submitted ? <div className="mt-8 rounded-2xl bg-amber-50 p-5 text-amber-900"><CheckCircle2 className="mb-3 text-amber-600" /><h3 className="font-bold">Application received</h3><p className="mt-2 text-sm leading-6">Your officer account is pending admin approval. We will email you when your access is ready.</p><Link to="/login" className="mt-4 inline-block text-sm font-bold underline">Return to sign in</Link></div> : <form onSubmit={handleSubmit(() => setSubmitted(true))} noValidate className="mt-7 space-y-4"><label className="text-sm font-medium text-slate-700">Full name<input className={fieldClass} {...register('name')} /></label><ErrorText message={errors.name?.message} /><label className="text-sm font-medium text-slate-700">Email address<input className={fieldClass} type="email" {...register('email')} /></label><ErrorText message={errors.email?.message} />{type === 'officer' && <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Organization<input className={fieldClass} {...register('organization')} /></label><label className="text-sm font-medium text-slate-700">Designation<input className={fieldClass} {...register('designation')} /></label><label className="text-sm font-medium text-slate-700 sm:col-span-2">Jurisdiction<input className={fieldClass} placeholder="District or ward" {...register('jurisdiction')} /></label><ErrorText message={errors.organization?.message || errors.designation?.message || errors.jurisdiction?.message} /></div>}<PasswordField register={register} error={errors.password} /><Button type="submit" className="mt-3 w-full">Create account</Button><p className="text-center text-sm text-slate-500">Already registered? <Link to="/login" className="font-semibold text-primary">Sign in</Link></p></form>}</AuthLayout>; }
const emailSchema = z.object({ email: z.string().email('Enter a valid email address') });
export function ForgotPassword() { const [sent, setSent] = useState(false); const { register, handleSubmit, formState: { errors } } = useForm({ resolver: zodResolver(emailSchema) }); return <AuthLayout eyebrow="Account recovery" title="Forgot your password?" subtitle="Enter your email and we will send a secure reset link.">{sent ? <div className="rounded-2xl bg-teal-50 p-5 text-teal-900"><Mail className="mb-3 text-primary" /><h3 className="font-bold">Check your inbox</h3><p className="mt-2 text-sm leading-6">If an account exists for that email, a reset link is on its way.</p><Link to="/login" className="mt-4 inline-block text-sm font-bold text-primary underline">Back to sign in</Link></div> : <form onSubmit={handleSubmit(() => setSent(true))}><label className="text-sm font-medium text-slate-700">Email address<input className={fieldClass} type="email" {...register('email')} /></label><ErrorText message={errors.email?.message} /><Button type="submit" className="mt-6 w-full">Send reset link</Button><Link to="/login" className="mt-6 flex items-center justify-center gap-2 text-sm font-semibold text-primary"><ArrowLeft size={16} />Back to sign in</Link></form>}</AuthLayout>; }
const resetSchema = z.object({ password: z.string().min(8, 'Password must be at least 8 characters'), confirm: z.string() }).refine((data) => data.password === data.confirm, { path: ['confirm'], message: 'Passwords do not match' });
export function ResetPassword() { const { token } = useParams(); const navigate = useNavigate(); const { register, handleSubmit, formState: { errors } } = useForm({ resolver: zodResolver(resetSchema) }); return <AuthLayout eyebrow="New password" title="Set a new password" subtitle={`Reset link ${token ? 'verified' : 'ready'} · Choose something strong and memorable.`}><form onSubmit={handleSubmit(() => navigate('/login'))} className="space-y-5"><PasswordField register={register} error={errors.password} /><PasswordField register={register} error={errors.confirm} name="confirm" label="Confirm password" /><Button type="submit" className="w-full">Update password</Button></form></AuthLayout>; }
