import { Bell, CheckCheck, ChevronRight, Filter, LoaderCircle } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../services/api';
import { NotificationIcon } from '../components/NotificationBell';
import { notificationLabels, relativeTime } from '../utils/notifications';

const tabs = [['ALL', 'All'], ['UNREAD', 'Unread'], ['NEW_REPORT', 'New reports'], ['CASE_ASSIGNED', 'Assignments'], ['STATUS_CHANGED', 'Status changes'], ['FOLLOW_UP_DUE', 'Follow-ups']];
export default function Notifications() {
  const navigate = useNavigate(); const [items, setItems] = useState([]); const [tab, setTab] = useState('ALL'); const [page, setPage] = useState(0); const [hasMore, setHasMore] = useState(true); const [loading, setLoading] = useState(true); const sentinel = useRef(null);
  const load = async nextPage => { setLoading(true); try { const response = await api.get('/notifications', { params: { page: nextPage, size: 20 } }); const data = response.data.data || {}; setItems(current => nextPage ? [...current, ...(data.content || [])] : data.content || []); setHasMore(!data.last); setPage(nextPage); } catch { setHasMore(false); } finally { setLoading(false); } };
  useEffect(() => { let cancelled = false; api.get('/notifications', { params: { page: 0, size: 20 } }).then(response => { if (cancelled) return; const data = response.data.data || {}; setItems(data.content || []); setHasMore(!data.last); setPage(0); }).catch(() => setHasMore(false)).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, []);
  useEffect(() => { const observer = new IntersectionObserver(entries => { if (entries[0].isIntersecting && hasMore && !loading) load(page + 1); }, { rootMargin: '180px' }); if (sentinel.current) observer.observe(sentinel.current); return () => observer.disconnect(); }, [hasMore, loading, page]);
  const visible = items.filter(item => tab === 'ALL' || (tab === 'UNREAD' ? !item.isRead : item.type === tab));
  const select = async item => { if (!item.isRead) { await api.put(`/notifications/${item.id}/read`).catch(() => {}); setItems(current => current.map(value => value.id === item.id ? { ...value, isRead: true } : value)); } if (item.relatedCaseId) navigate(`/cases/${item.relatedCaseId}`); };
  const markAll = async () => { await api.put('/notifications/read-all').catch(() => {}); setItems(current => current.map(item => ({ ...item, isRead: true }))); };
  return <div className="space-y-7 pb-10"><header className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-teal-700"><Bell size={15} />Your updates</div><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-900">Notifications</h1><p className="mt-2 text-sm text-slate-500">The important moments your casework should not miss.</p></div><button onClick={markAll} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm font-bold text-slate-600 shadow-sm hover:border-teal-300"><CheckCheck size={16} />Mark all as read</button></header><div className="flex items-center gap-2 overflow-x-auto border-b border-slate-200"><Filter size={16} className="shrink-0 text-slate-400" />{tabs.map(([key, label]) => <button key={key} onClick={() => setTab(key)} className={`shrink-0 border-b-2 px-3 py-3 text-xs font-bold ${tab === key ? 'border-[#c94b32] text-teal-800' : 'border-transparent text-slate-400 hover:text-slate-700'}`}>{label}</button>)}</div><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><p className="text-xs font-bold text-slate-500">{tab === 'ALL' ? 'All notifications' : tab === 'UNREAD' ? 'Unread notifications' : notificationLabels[tab]}</p></div>{visible.length ? visible.map(item => <button key={item.id} onClick={() => select(item)} className={`flex w-full gap-4 border-b border-slate-100 p-5 text-left transition hover:bg-slate-50 ${!item.isRead ? 'bg-teal-50/30' : ''}`}><NotificationIcon type={item.type} /><span className="min-w-0 flex-1"><span className={`block text-sm ${item.isRead ? 'font-semibold text-slate-700' : 'font-extrabold text-slate-900'}`}>{item.title || notificationLabels[item.type]}</span><span className="mt-1 block text-sm leading-6 text-slate-500">{item.message}</span><span className="mt-2 block text-xs font-semibold text-slate-400">{relativeTime(item.createdAt)}<span className="mx-2 text-slate-300">·</span>{new Date(item.createdAt).toLocaleString('en-IN')}</span></span><ChevronRight size={18} className="mt-2 shrink-0 text-slate-300" /></button>) : !loading && <div className="px-6 py-16 text-center text-sm text-slate-400">No notifications in this view.</div>}<div ref={sentinel} className="flex h-16 items-center justify-center">{loading && <LoaderCircle size={18} className="animate-spin text-teal-600" />}{!hasMore && items.length > 0 && <span className="text-xs font-semibold text-slate-400">You have reached the end.</span>}</div></section></div>;
}