import { CalendarDays, ChevronRight, CircleUserRound, Clock3, HeartHandshake, Search, Sparkles } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../services/api';
import { daysInProgram, phaseLabels, phases } from '../utils/rehabilitation';

const sampleCases = [
  { id: 8, caseReportId: 44, childAlias: 'River-17', rehabilitationCenterId: 2, startDate: '2026-08-04', currentPhase: 'MEDICAL_ASSESSMENT', assignedCounsellorId: 12 },
  { id: 9, caseReportId: 45, childAlias: 'Marigold-08', rehabilitationCenterId: 1, startDate: '2026-07-12', currentPhase: 'COUNSELLING', assignedCounsellorId: 7 },
  { id: 10, caseReportId: 46, childAlias: 'Kite-24', rehabilitationCenterId: 2, startDate: '2026-06-18', currentPhase: 'FAMILY_REINTEGRATION', assignedCounsellorId: 12 },
  { id: 11, caseReportId: 47, childAlias: 'Mango-31', rehabilitationCenterId: 1, startDate: '2026-04-02', currentPhase: 'COMPLETED', assignedCounsellorId: 7 },
];
export function PhaseStepper({ currentPhase, compact = false }) { const active = phases.indexOf(currentPhase); return <div className={`flex items-start ${compact ? 'gap-1' : 'gap-2'}`}>{phases.map((phase, index) => <div key={phase} className="flex min-w-0 flex-1 items-start"><div className="flex min-w-0 flex-1 flex-col items-center"><span className={`grid h-7 w-7 place-items-center rounded-full text-[10px] font-bold ring-4 ring-white ${index <= active ? 'bg-gradient-to-br from-emerald-500 to-teal-700 text-white' : 'bg-slate-100 text-slate-400'}`}>{index < active ? '✓' : index + 1}</span><span className={`mt-2 text-center text-[9px] font-bold leading-3 ${index <= active ? 'text-teal-800' : 'text-slate-400'}`}>{phaseLabels[phase]}</span></div>{index < phases.length - 1 && <span className={`mt-3 h-0.5 flex-1 ${index < active ? 'bg-teal-500' : 'bg-slate-200'}`} />}</div>)}</div>; }
function Counsellor({ id }) { return <span className="flex items-center gap-2 text-xs font-semibold text-slate-600"><span className="grid h-8 w-8 place-items-center rounded-full bg-teal-100 text-teal-700"><CircleUserRound size={19} /></span>{id ? 'Ananya Rao' : 'Unassigned'}</span>; }

export default function RehabilitationManagement() {
  const [cases, setCases] = useState(sampleCases); const [query, setQuery] = useState(''); const [phase, setPhase] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { api.get('/rehabilitation').then(response => { if (Array.isArray(response.data.data)) setCases(response.data.data); }).catch(() => {}).finally(() => setLoading(false)); }, []);
  const visible = useMemo(() => cases.filter(item => (!query || item.childAlias.toLowerCase().includes(query.toLowerCase())) && (!phase || item.currentPhase === phase)), [cases, phase, query]);
  return <div className="space-y-7 pb-8"><header className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-emerald-700"><HeartHandshake size={15} />Pathways to safety</div><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-900">Rehabilitation</h1><p className="mt-2 text-sm text-slate-500">Support plans, progress, and the people walking alongside each child.</p></div><Link to="/rehabilitation/follow-ups" className="inline-flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2.5 text-sm font-bold text-emerald-800"><Clock3 size={17} />Follow-ups due</Link></header><div className="grid gap-4 sm:grid-cols-3"><Stat icon={HeartHandshake} label="Active programs" value={cases.filter(item => item.currentPhase !== 'COMPLETED').length} tone="emerald" /><Stat icon={Clock3} label="Follow-ups this week" value="06" tone="amber" /><Stat icon={Sparkles} label="Completed this year" value={18} tone="sky" /></div><div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm sm:flex-row"><div className="relative flex-1"><Search size={18} className="absolute left-3 top-2.5 text-slate-400" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search privacy alias..." className="w-full rounded-xl bg-slate-50 py-2.5 pl-10 pr-3 text-sm outline-none focus:ring-2 focus:ring-emerald-100" /></div><select value={phase} onChange={event => setPhase(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-bold text-slate-600 outline-none"><option value="">All phases</option>{phases.map(item => <option key={item} value={item}>{phaseLabels[item]}</option>)}</select></div>{loading ? <p className="py-10 text-center text-sm text-slate-500">Loading rehabilitation programs...</p> : <div className="grid gap-5 xl:grid-cols-2">{visible.map(item => <RehabCard key={item.id} item={item} />)}</div>}{!loading && !visible.length && <Empty text="No rehabilitation cases match these filters." />}</div>;
}
function RehabCard({ item }) { return <Link to={`/rehabilitation/${item.id}`} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-emerald-300 hover:shadow-md"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br from-emerald-50 to-teal-100 text-teal-700"><CircleUserRound size={27} /></span><div><p className="font-mono text-xs font-bold text-teal-700">{item.childAlias}</p><p className="mt-1 text-xs text-slate-500">Program #{String(item.id).padStart(3, '0')}</p></div></div><ChevronRight size={19} className="text-slate-300 transition group-hover:translate-x-1 group-hover:text-teal-600" /></div><div className="mt-7"><PhaseStepper currentPhase={item.currentPhase} /></div><div className="mt-7 flex items-center justify-between border-t border-slate-100 pt-4"><Counsellor id={item.assignedCounsellorId} /><span className="flex items-center gap-1.5 text-xs font-bold text-slate-500"><CalendarDays size={14} />{daysInProgram(item.startDate)} days in program</span></div></Link>; }
function Stat({ icon: Icon, label, value, tone }) { const colors = { emerald: 'bg-emerald-50 text-emerald-700', amber: 'bg-amber-50 text-amber-700', sky: 'bg-sky-50 text-sky-700' }; return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className={`grid h-9 w-9 place-items-center rounded-xl ${colors[tone]}`}><Icon size={18} /></div><p className="mt-4 text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-800">{value}</p></div>; }
export function Empty({ text }) { return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center text-sm text-slate-500">{text}</div>; }