import 'leaflet/dist/leaflet.css';
import { ArrowLeft, ArrowRight, Check, CheckCircle2, Clipboard, FileText, UploadCloud, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { CircleMarker, MapContainer, TileLayer, useMapEvents } from 'react-leaflet';
import api from '../services/api';

const steps = ['Child details', 'Location', 'Incident', 'Evidence', 'Reporter', 'Review'];
const initial = { childName: '', approxAge: '', gender: '', childDescription: '', locationAddress: '', latitude: '', longitude: '', district: '', state: '', incidentDescription: '', employerOrLocationDetails: '', dateOfIncident: '', urgencyLevel: 'MEDIUM', anonymous: false, reporterName: '', reporterEmail: '', reporterPhone: '' };
function Field({ label, value, onChange, type = 'text', placeholder, required = false }) { return <label className="block text-sm font-semibold text-slate-700">{label}{required && <span className="text-[#c94b32]"> *</span>}<input type={type} value={value} onChange={onChange} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 font-normal outline-none transition focus:border-teal-600 focus:ring-4 focus:ring-teal-50" /></label>; }
function MapPicker({ position, setPosition }) { useMapEvents({ click(event) { setPosition([event.latlng.lat, event.latlng.lng]); } }); return position ? <CircleMarker center={position} radius={10} pathOptions={{ color: '#c94b32', fillColor: '#f4a261', fillOpacity: .9 }} /> : null; }
function Section({ title, note, children }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-xl font-bold text-[#0b4f4b]">{title}</h2>{note && <p className="mt-1 text-sm text-slate-500">{note}</p>}<div className="mt-6 grid gap-5">{children}</div></section>; }

export default function ReportCase() {
  const [step, setStep] = useState(0); const [form, setForm] = useState(initial); const [files, setFiles] = useState([]); const [submitted, setSubmitted] = useState(null); const [error, setError] = useState('');
  const update = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.type === 'checkbox' ? event.target.checked : event.target.value }));
  const position = useMemo(() => form.latitude && form.longitude ? [Number(form.latitude), Number(form.longitude)] : null, [form.latitude, form.longitude]);
  const setPosition = ([latitude, longitude]) => setForm((current) => ({ ...current, latitude: latitude.toFixed(6), longitude: longitude.toFixed(6) }));
  const addFiles = (event) => setFiles((current) => [...current, ...Array.from(event.target.files || [])].slice(0, 5));
  const removeFile = (index) => setFiles((current) => current.filter((_, fileIndex) => fileIndex !== index));
  const submit = async () => { setError(''); try { const data = new FormData(); Object.entries(form).forEach(([key, value]) => { if (!['reporterName', 'reporterEmail', 'reporterPhone'].includes(key)) data.append(key, value); }); files.forEach((file) => data.append('files', file)); const response = await api.post('/reports', data, { headers: { 'Content-Type': 'multipart/form-data' } }); setSubmitted(response.data.data); } catch (requestError) { setError(requestError.response?.data?.message || 'We could not submit the report. Please try again.'); } };
  const copy = () => navigator.clipboard?.writeText([submitted.caseNumber, submitted.trackingCode].filter(Boolean).join(' · '));
  if (submitted) return <main className="min-h-screen bg-[#fffaf2] px-5 py-12 sm:px-8"><div className="mx-auto max-w-xl rounded-3xl bg-white p-7 text-center shadow-xl shadow-amber-900/10 sm:p-12"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-50 text-emerald-600"><CheckCircle2 size={34} /></div><p className="mt-6 text-sm font-bold uppercase tracking-[.16em] text-emerald-700">Report received</p><h1 className="mt-2 text-3xl font-bold text-[#0b4f4b]">Thank you for speaking up.</h1><p className="mt-3 leading-7 text-slate-600">Every report matters. Please save these details so you can follow the progress of your report.</p><div className="mt-8 rounded-2xl bg-[#f1f8f5] p-5 text-left"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Case number</p><p className="mt-1 break-all text-2xl font-bold tracking-wide text-[#0b4f4b]">{submitted.caseNumber}</p>{submitted.trackingCode && <><p className="mt-5 text-xs font-bold uppercase tracking-wider text-slate-500">Tracking code</p><p className="mt-1 break-all text-2xl font-bold tracking-wide text-[#0b4f4b]">{submitted.trackingCode}</p></>}<button onClick={copy} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-white px-3 py-2 text-sm font-bold text-[#0b4f4b] shadow-sm"><Clipboard size={16} />Copy details</button></div><Link to="/track-case" className="mt-7 inline-flex font-bold text-[#0b4f4b] underline underline-offset-4">Track your report</Link></div></main>;
  return <main className="min-h-screen bg-[#fffaf2] px-4 py-6 sm:px-8 sm:py-10"><div className="mx-auto max-w-4xl"><header className="mb-8 flex items-center justify-between"><Link to="/" className="flex items-center gap-2 font-bold text-[#0b4f4b]"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#0b4f4b] text-amber-300">C</span>CLRMS</Link><Link to="/track-case" className="text-sm font-bold text-slate-600">Track a case</Link></header><div className="mb-8"><p className="text-sm font-bold uppercase tracking-[.16em] text-[#c94b32]">A calm place to begin</p><h1 className="mt-2 text-3xl font-bold text-[#0b4f4b] sm:text-4xl">Report a case</h1><p className="mt-2 text-slate-600">Thank you for helping protect a child. Share what you know, at your own pace.</p></div><div className="mb-8 grid grid-cols-3 gap-2 sm:grid-cols-6">{steps.map((label, index) => <button key={label} onClick={() => index <= step && setStep(index)} className={`border-t-4 pt-3 text-left text-xs font-bold sm:text-sm ${index <= step ? 'border-[#c94b32] text-[#0b4f4b]' : 'border-slate-200 text-slate-400'}`}><span className="mr-1">{index + 1}.</span>{label}</button>)}</div>{error && <div className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    {step === 0 && <Section title="Tell us about the child" note="It's okay if you don't know exact details. Approximate information is helpful too."><div className="grid gap-5 sm:grid-cols-2"><Field label="Child's name" value={form.childName} onChange={update('childName')} placeholder="Optional" /><Field label="Approximate age" value={form.approxAge} onChange={update('approxAge')} type="number" placeholder="Optional" /><Field label="Gender" value={form.gender} onChange={update('gender')} placeholder="Optional" /><Field label="What did the child look like?" value={form.childDescription} onChange={update('childDescription')} placeholder="Optional description" /></div></Section>}
    {step === 1 && <Section title="Where did this happen?" note="A nearby landmark or approximate pin is enough."><Field label="Address or landmark" value={form.locationAddress} onChange={update('locationAddress')} placeholder="Street, landmark, or neighbourhood" required /><div className="h-72 overflow-hidden rounded-xl border border-slate-200"><MapContainer center={position || [20.5937, 78.9629]} zoom={position ? 14 : 5} scrollWheelZoom className="h-full w-full"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><MapPicker position={position} setPosition={setPosition} /></MapContainer></div><p className="text-xs text-slate-500">Click the map to place a pin. Coordinates: {position ? `${form.latitude}, ${form.longitude}` : 'not selected yet'}</p><div className="grid gap-5 sm:grid-cols-2"><Field label="District" value={form.district} onChange={update('district')} placeholder="District" /><Field label="State" value={form.state} onChange={update('state')} placeholder="State" /></div></Section>}
    {step === 2 && <Section title="What happened?" note="Your words help the response team understand what support may be needed."><Field label="Incident description" value={form.incidentDescription} onChange={update('incidentDescription')} placeholder="Tell us what you saw or learned" required /><Field label="Employer or location details" value={form.employerOrLocationDetails} onChange={update('employerOrLocationDetails')} placeholder="Optional details" /><div className="grid gap-5 sm:grid-cols-2"><Field label="Date of incident" value={form.dateOfIncident} onChange={update('dateOfIncident')} type="date" /><label className="text-sm font-semibold text-slate-700">Urgency<select value={form.urgencyLevel} onChange={update('urgencyLevel')} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 outline-none"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label></div></Section>}
    {step === 3 && <Section title="Add supporting evidence" note="You can share photos, videos, or documents if it feels safe. This is optional."><label className="flex min-h-40 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-teal-200 bg-teal-50/40 p-6 text-center"><UploadCloud className="text-[#0b4f4b]" size={30} /><span className="mt-3 font-bold text-[#0b4f4b]">Drop files here or browse</span><span className="mt-1 text-xs text-slate-500">JPG, PNG, MP4, PDF · up to 10MB each</span><input type="file" multiple accept=".jpg,.jpeg,.png,.mp4,.pdf" onChange={addFiles} className="hidden" /></label><div className="grid gap-3">{files.map((file, index) => <div key={`${file.name}-${index}`} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3"><FileText size={19} className="text-[#c94b32]" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{file.name}</p><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-full bg-emerald-500" /></div></div><button onClick={() => removeFile(index)} aria-label={`Remove ${file.name}`}><X size={17} className="text-slate-400" /></button></div>)}</div></Section>}
    {step === 4 && <Section title="About you" note="Your details help us follow up. You can also report anonymously."><label className="flex items-center justify-between rounded-2xl border border-amber-200 bg-amber-50 p-4"><span><span className="block font-bold text-amber-950">Report Anonymously</span><span className="mt-1 block text-xs text-amber-800">Your name and contact details will not be attached to this report.</span></span><input type="checkbox" checked={form.anonymous} onChange={update('anonymous')} className="h-5 w-5 accent-[#c94b32]" /></label>{!form.anonymous && <div className="grid gap-5 sm:grid-cols-2"><Field label="Your name" value={form.reporterName} onChange={update('reporterName')} placeholder="Full name" /><Field label="Email address" value={form.reporterEmail} onChange={update('reporterEmail')} type="email" placeholder="you@example.org" /><Field label="Phone number" value={form.reporterPhone} onChange={update('reporterPhone')} placeholder="Optional" /></div>}</Section>}
    {step === 5 && <Section title="Review your report" note="Please check the information below before sending it to the response team."><div className="grid gap-4 text-sm"><p><b>Location:</b> {form.locationAddress || 'Not provided'}{form.district && `, ${form.district}`}</p><p><b>Incident:</b> {form.incidentDescription || 'Not provided'}</p><p><b>Urgency:</b> {form.urgencyLevel}</p><p><b>Evidence:</b> {files.length ? `${files.length} file${files.length > 1 ? 's' : ''}` : 'None added'}</p><p><b>Reporter:</b> {form.anonymous ? 'Anonymous' : (form.reporterName || 'Citizen')}</p></div></Section>}
    <div className="mt-6 flex justify-between"><button disabled={!step} onClick={() => setStep((current) => current - 1)} className="inline-flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-bold text-slate-600 disabled:invisible"><ArrowLeft size={17} />Back</button>{step < steps.length - 1 ? <button onClick={() => setStep((current) => current + 1)} className="inline-flex items-center gap-2 rounded-xl bg-[#0b4f4b] px-5 py-3 text-sm font-bold text-white">Continue <ArrowRight size={17} /></button> : <button onClick={submit} className="inline-flex items-center gap-2 rounded-xl bg-[#c94b32] px-5 py-3 text-sm font-bold text-white"><Check size={17} />Submit report</button>}</div>
    </div></main>;
}